# MQTT Broker 的 IP 地址
broker_ip = "localhost"

# MQTT Broker 的端口号（通常为 1883）
broker_port = 1883

# MQTT 用户名（可选，如果不需要认证请注释掉）
# username = "your_username"

# MQTT 密码（可选，如果不需要认证请注释掉）
# password = "your_password"
