name: Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Show toolchain versions
        shell: pwsh
        run: |
          rustc -vV
          cargo -vV
      - name: Build (capture log)
        shell: pwsh
        run: |
          cargo build --verbose *>&1 | Tee-Object -FilePath build.log
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      - name: Upload build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
